version: '3.8'

services:
  temporal:
    image: temporalio/auto-setup:1.24
    ports:
      - '7233:7233'
      - '8233:8233'
    environment:
      - CASSANDRA_PORT=9042
      - POSTGRES_PORT=5432
      - KAFKA_PORT=9092
      - OPENSEARCH_PORT=9200
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    networks:
      - fkred_default

networks:
  fkred_default:
    driver: bridge